services:
  postgres:
    image: postgres:17
    container_name: hutep_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: hutep_bot
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WEBHOOK_URL: ${WEBHOOK_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      VPN_BASE_URL: ${VPN_BASE_URL}
      VPN_API_TOKEN: ${VPN_API_TOKEN}
      VPN_BASE_SUB: ${VPN_BASE_SUB}
      CRYPTO_BOT_TOKEN: ${CRYPTO_BOT_TOKEN}
    command: sh -c "alembic upgrade head && python bot.py"

  caddy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - bot

volumes:
  postgres_data:
  caddy_data:
  caddy_config: