"""add payments and fix models

Revision ID: 27d6cbed52d7
Revises: a66d0cad6511
Create Date: 2026-05-31 17:50:10.869853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d6cbed52d7'
down_revision: Union[str, Sequence[str], None] = 'a66d0cad6511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('telegram_payment_charge_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'telegram_payment_charge_id')
    # ### end Alembic commands ###
