"""add payments and fix models

Revision ID: a66d0cad6511
Revises: 2525ca254148
Create Date: 2026-05-31 17:41:33.050201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a66d0cad6511'
down_revision: Union[str, Sequence[str], None] = '2525ca254148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payments', sa.Column('is_successful', sa.Boolean(), nullable=False))
    op.drop_column('payments', 'is_successfull')
    op.alter_column('subscriptions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('payments', sa.Column('is_successfull', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'is_successful')
    op.drop_column('payments', 'amount')
    # ### end Alembic commands ###
