"""add external_id and status to payments

Revision ID: dcb0e1eca570
Revises: f94c35ff5eb5
Create Date: 2026-06-02 18:19:29.954895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb0e1eca570'
down_revision: Union[str, Sequence[str], None] = 'f94c35ff5eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('payments', sa.Column('external_id', sa.String(length=128), nullable=True))
    op.add_column('payments', sa.Column('status', sa.String(length=16), nullable=True))
    op.execute("UPDATE payments SET external_id = 'legacy:' || id::text WHERE external_id IS NULL")
    op.execute("UPDATE payments SET status = CASE WHEN is_successful THEN 'successful' ELSE 'pending' END WHERE status IS NULL")
    op.alter_column('payments', 'external_id', nullable=False)
    op.alter_column('payments', 'status', nullable=False)
    op.create_unique_constraint('uq_payments_provider_external_id', 'payments', ['provider', 'external_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payments_provider_external_id', 'payments', type_='unique')
    op.drop_column('payments', 'status')
    op.drop_column('payments', 'external_id')
    # ### end Alembic commands ###
