"""empty message

Revision ID: f94c35ff5eb5
Revises: 7c3ab82358d1
Create Date: 2026-06-02 01:35:22.833295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94c35ff5eb5'
down_revision: Union[str, Sequence[str], None] = '7c3ab82358d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('sub_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'sub_id')
    # ### end Alembic commands ###
